AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'config/initializers/devise.rb'
    - 'db/migrate/*'
    - 'Guardfile'

Documentation:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
