inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'config/initializers/devise.rb'
    - 'db/migrate/*'
    - 'Guardfile'
    - 'bin/*'
    - 'config/*'
    - 'Rakefile'

Documentation:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'feature']

Metrics/ClassLength:
  Exclude:
    - 'app/lib/kuwinda/repository/target_db.rb'

Metrics/ModuleLength:
  Max: 200
  Exclude:
    - 'spec/unit/lib/kuwinda/repository/target_db_spec.rb'

Layout/FirstArrayElementIndentation:
  Exclude:
    - 'db/seeds.rb'
