default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['CLIENT_DATABASE_HOST'] %>
  username: <%= ENV['CLIENT_DATABASE_USER'] %>
  password: <%= ENV['CLIENT_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV['CLIENT_DATABASE_URL'] %>

test:
  <<: *default
  database: <%= ENV['CLIENT_DATABASE_DEVELOPMENT'] %>
