default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['KUWINDA_DATABASE_HOST'] %>
  username: <%= ENV['KUWINDA_DATABASE_USER'] %>
  password: <%= ENV['KUWINDA_DATABASE_PASSWORD'] %>
  port: <%= ENV['KUWINDA_DATABASE_PORT'] { 5432 } %>

development:
  <<: *default
  database: kuwinda_development

test:
  <<: *default
  database: kuwinda_test

production:
  <<: *default
  database: kuwinda_production
